import type { BubbleColor, Cell, SpecialTile, WindStrip } from './board';
import type { LevelDefinition } from './levels-v3';

// Every layout is authored separately. Row letters are colors; lowercase letters
// contain bee friends. These chapters continue the existing thirty-level journey.
export type ExpansionChapter = 'rosewood' | 'echo-glen' | 'braided-brook' | 'lantern-wood' | 'high-canopy' | 'starlit-orchard' | 'homecoming';
export const expansionChapters: { id: ExpansionChapter; name: string; subtitle: string; first: number; last: number }[] = [
  { id: 'rosewood', name: 'Rosewood Rise', subtitle: 'Little buds, lovely second chances', first: 31, last: 40 },
  { id: 'echo-glen', name: 'Echo Glen', subtitle: 'Let a little color travel', first: 41, last: 50 },
  { id: 'braided-brook', name: 'Braided Brook', subtitle: 'Two new tricks find a rhythm', first: 51, last: 60 },
  { id: 'lantern-wood', name: 'Lantern Wood', subtitle: 'Warm lights and winding ways', first: 61, last: 70 },
  { id: 'high-canopy', name: 'High Canopy', subtitle: 'A little courage, a lovely view', first: 71, last: 80 },
  { id: 'starlit-orchard', name: 'Starlit Orchard', subtitle: 'Make a wish and plan a path', first: 81, last: 90 },
  { id: 'homecoming', name: 'Homecoming Hollow', subtitle: 'Bring every little friend along', first: 91, last: 100 }
];

const bud = (row: number, col: number, nextColor: BubbleColor): SpecialTile => ({ row, col, kind: 'bud', nextColor });
const echo = (row: number, col: number): SpecialTile => ({ row, col, kind: 'echo' });
const hc = (row: number, col: number): SpecialTile => ({ row, col, kind: 'honeycomb' });
const dew = (row: number, col: number): SpecialTile => ({ row, col, kind: 'dew' });
const pollen = (row: number, col: number): SpecialTile => ({ row, col, kind: 'pollen' });
const chameleon = (row: number, col: number, alternate: BubbleColor): SpecialTile => ({ row, col, kind: 'bloom', alternate });
const echoes = (row: number, ...cols: number[]): SpecialTile[] => cols.map(col => echo(row, col));
const path = (...cells: [number, number][]): Cell[] => cells.map(([row, col]) => ({ row, col }));

function level(id: number, name: string, place: string, rows: string[], par: number, hint: string,
  options: { specials?: SpecialTile[]; wind?: WindStrip; flightPath?: Cell[]; tutorial?: string; shots?: number } = {}): LevelDefinition {
  const chapter = expansionChapters.find(item => id >= item.first && id <= item.last)!.id;
  const specials = options.specials ?? [];
  const specialColors = specials.flatMap(tile => {
    if (tile.kind === 'bloom') return [tile.alternate];
    if (tile.kind === 'bud') return [tile.nextColor];
    return [];
  });
  return {
    id, name, place, chapter, rows, par,
    shots: options.shots ?? par + (id <= 42 || id >= 91 ? 6 : 5),
    colors: [...new Set([...rows.join('').toUpperCase().replace(/\./g, ''), ...specialColors])] as BubbleColor[],
    specials, wind: options.wind, flightPath: options.flightPath,
    hint, tutorial: options.tutorial, seed: id * 179 + 43
  };
}

export const expansionLevels: LevelDefinition[] = [
  // Rosewood: the first two boards isolate buds, including ceiling-anchored bees
  // that cannot be rescued just by dropping the surrounding canopy.
  level(31, 'A Budding Friendship', 'The rosewood welcome',
    ['..RrR....', '..GGG...', '...YY....', '...yY...'], 10,
    'The little red bud keeps its bee after the first match. Its green rim tells you the color to match next.',
    { specials: [bud(0, 3, 'G')], tutorial: 'Rose buds have two layers. Match the color showing now to open the bud; it stays in place and becomes the color on its small rim. Match that new color to rescue the bee. Buds change only when matched.' }),
  level(32, 'Two Second Chances', 'The rosewood fork',
    ['RrR...GgG', 'RR....GG', '.YY...YY.', '..yy.yy.'], 10,
    'Practice on either branch. Both buds open into yellow; check the next bubble before choosing a side.',
    { specials: [bud(0, 1, 'Y'), bud(0, 7, 'Y')] }),
  level(33, 'Petals at the Window', 'The rosewood hedge',
    ['RRrYYYgGG', 'RRYYYYGG', '.RR...GG.', '.BB..BB.', '..Bb.bB..'], 11,
    'Two buds hold the upper bees. The lower blue pockets can fall when their branches are cut.',
    { specials: [bud(0, 2, 'Y'), bud(0, 6, 'Y'), pollen(4, 3)] }),
  level(34, 'The Little Rose Stair', 'The climbing-rose steps',
    ['...GgG...', '...YY...', '..RRYY...', '..RrYY..', '.PP..BB..', '.pP..Bb.'], 11,
    'Work up the uneven steps. The top bud turns yellow, so leave yourself a clear way back to it.',
    { specials: [bud(0, 4, 'Y'), dew(3, 3)] }),
  level(35, 'Under the Rose Arch', 'The pink garden gate',
    ['OoO...PpP', 'OO.YY.PP', '.OOYYYPP.', '..YyyY..', '...GGG...', '...gG...'], 12,
    'The two hanging sides share a yellow arch. Opening either bud changes it to green; the pollen below is a pleasant detour.',
    { specials: [bud(0, 1, 'G'), bud(0, 7, 'G'), hc(1, 2), hc(1, 5), pollen(5, 3)] }),
  level(36, 'Mabel and the Rosebud', 'The rosewood flight lane',
    ['...rRR...', '..YYGG..', '..YYGG...', '..BBPP..', '..BBPP...', '..YYGG..', '.........'], 12,
    'Clear Mabel’s gentle bend from below. The red bud at her destination must open and then be matched again.',
    { specials: [bud(0, 3, 'Y')], flightPath: path([6, 3], [5, 3], [4, 4], [3, 4], [2, 4], [1, 3], [0, 3]) }),
  level(37, 'A Door in the Hedge', 'The thorn-free shortcut',
    ['RRrOOOGGG', 'RR..OOGG', '.RR...GG.', '.YY..BB.', '.YYY.BBB.', '..yY.Bb.'], 12,
    'The honeycomb makes a doorway with two supports. A bank can open a side while you prepare the blue layer of the top bud.',
    { specials: [bud(0, 2, 'B'), hc(2, 3), hc(2, 4), hc(2, 5)] }),
  level(38, 'The Rosewood Chandelier', 'The petal picnic',
    ['...PpP...', '...PP...', '..GGGG...', '..GgGG..', '.RRYYBB..', '.rRyyBb.', '..R...B..'], 13,
    'The picnic hangs from one bud. Clear its green collar carefully, then return to the yellow layer at the ceiling.',
    { specials: [bud(0, 4, 'Y'), dew(3, 3), pollen(5, 4)] }),
  level(39, 'Petals in a Breeze', 'The rosewood overlook',
    ['rRRYYYgGG', 'RR.PP.GG', '.RRPPPgg.', '.YY..BB.', '..YYBBB..', '..yYBb..'], 13,
    'The left bud becomes purple and the right becomes blue. The chameleon changes after each shot, so plan the color you want to leave showing.',
    { specials: [bud(0, 0, 'P'), bud(0, 6, 'B'), chameleon(1, 4, 'Y')] }),
  level(40, 'The Rosewood Farewell', 'The brook beside the roses',
    ['OoOYYYBbB', 'OOGGGGBB', '.OO...BB.', '.PP..PP.', '..PPGPP..', '..pPgp..', '...GGG...'], 14,
    'Open the two ceiling buds, then choose a support for the hanging petals. The bottom green raft tries to move every two shots.',
    { specials: [bud(0, 1, 'G'), bud(0, 7, 'P'), dew(0, 4), pollen(5, 2)], wind: { row: 6, start: 3, length: 3 } }),

  // Echo Glen: isolated echo practice precedes any mixture with buds.
  level(41, 'Hello, Little Echo', 'The echo-glen entrance',
    ['...PpP...', '...RR...', '...RR....', '...yY...'], 10,
    'Pop the red pair beneath the echo cluster. The touching echoes take that red color together and can make their own follow-on match.',
    { specials: [...echoes(0, 3, 4, 5)], tutorial: 'Echo bubbles carry a little ripple. When a popped color touches one echo, its whole connected echo cluster takes that color. If the new connected color group has three or more bubbles, it pops too. You can also match an echo’s visible color normally.' }),
  level(42, 'An Answer from Both Sides', 'The twin echo banks',
    ['PpP...BbB', 'RR....YY', '.RR...YYY', '..rr.yy.'], 10,
    'Try the left or right answer. A red pop can wake the purple echoes; a yellow pop can wake the blue ones.',
    { specials: [...echoes(0, 0, 1, 2), ...echoes(0, 6, 7, 8)] }),
  level(43, 'The Hollow’s Ripple', 'The hollow-log choir',
    ['...YyY...', '..PPPP..', '..Pp.P...', '..RRBB..', '..rrbb...'], 11,
    'One touching match can carry color through the bent echo cluster. The yellow bee above still needs its dew shell cracked.',
    { specials: [...echoes(1, 2, 3, 4, 5), ...echoes(2, 2, 3, 5), dew(0, 4)] }),
  level(44, 'Crescent of Replies', 'The crescent pond',
    ['RRR...GGG', 'RR....GG', '.PP...BB.', '.Pp..bB.', '..YY.YY..', '..yY.Yy.'], 11,
    'Each curved echo pocket has its own answer. Clear a yellow pair nearby, or use its visible color to open the pocket directly.',
    { specials: [...echoes(2, 1, 2), ...echoes(3, 1, 2), ...echoes(2, 6, 7), ...echoes(3, 5, 6)] }),
  level(45, 'The Lantern’s Answer', 'The hollow lantern',
    ['RRrYYYGGG', 'RRYYYYGG', '.RRBBBGG.', '..PpPP..', '...YYY...', '...yY...'], 12,
    'The yellow tassel touches the echo lantern. Open it from below, then find a clean bank to the upper red bee.',
    { specials: [...echoes(3, 2, 3, 4, 5), hc(2, 0), hc(2, 8), pollen(5, 3)] }),
  level(46, 'Mabel Hears the Way', 'The echo flight path',
    ['..GGPPP..', '..GGPP..', '..RRBB...', '..RRBB..', '...YYY...', '........'], 12,
    'The route climbs through blue into an echo gate. A nearby pop may open the whole purple cluster at once.',
    { specials: [...echoes(0, 4, 5, 6), ...echoes(1, 4, 5)], flightPath: path([5, 4], [4, 4], [3, 4], [2, 4], [1, 4], [0, 4]) }),
  level(47, 'Reed-Bed Chorus', 'The singing reeds',
    ['OOO.PPP..', 'OO..PP..', '.YY.PP...', '.YyPpP..', '..RR.BB..', '..rr.Bb.', '...R.B...'], 13,
    'The echo reed bends around a gap. A pop touching any part reaches the whole connected reed; the outside orange branch gives another approach.',
    { specials: [...echoes(0, 4, 5, 6), ...echoes(1, 4, 5), ...echoes(2, 4, 5), ...echoes(3, 3, 4, 5)] }),
  level(48, 'A Ripple Through the Gate', 'The comb-and-reed gate',
    ['RRRYyYBBB', 'RRPpPPBB', '.RR..BB..', '.GG..GG.', '..GGGGG..', '...gg...'], 13,
    'The comb cannot echo or color-match. Open the purple ripple above it, then cut whichever green support leaves the best path to the dew bee.',
    { specials: [...echoes(1, 2, 3, 4, 5), hc(2, 3), hc(2, 4), dew(0, 4)] }),
  level(49, 'A Reply on the Raft', 'The whispering water',
    ['RRR...YyY', 'RR.PP.YY', '.RRPPYY..', '..PpPP..', '..BBG....', '..BbG...'], 13,
    'The blue-and-green raft moves every two shots. Watch which color will touch the echo cluster after the move, and leave room for the upper dew bee.',
    { specials: [...echoes(3, 2, 3, 4, 5), dew(0, 7)], wind: { row: 4, start: 2, length: 3 } }),
  level(50, 'The Glen Sings Goodbye', 'The great echo arch',
    ['RRRYyYBBB', 'RRPPPPBB', '.RRPpBB..', '.GG..GG.', '..GGYGG..', '..gGYg..', '...YYY...', '...yY...'], 14,
    'The echo arch crosses the middle, while the yellow stem carries the lower picnic. Clear a route upward before returning to the dew bee.',
    { specials: [...echoes(1, 2, 3, 4, 5), ...echoes(2, 3, 4), hc(3, 3), hc(3, 4), dew(0, 4), pollen(6, 4)] }),

  // Braided Brook: practiced mechanics now form complementary rescue routes.
  level(51, 'Two Tricks, One Brook', 'The braided-brook welcome',
    ['RRr...PpP', 'RR....YY', '.RR...YY.', '.GG..BB.', '..gg.bb..'], 11,
    'The left bud opens into green. The right echo cluster can answer a yellow pop. Choose a side using both bubbles in your queue.',
    { specials: [bud(0, 2, 'G'), ...echoes(0, 6, 7, 8)], tutorial: 'You have met buds and echoes separately. Now try choosing a route: buds keep their next color until matched, while echoes borrow the color of a touching pop. Swapping still costs no shot.' }),
  level(52, 'A Pocket by the Water', 'The mossy brook pocket',
    ['..GgG....', '..GGYY..', '.PPGGYY..', '.PpRRR..', '..RRBB...', '..rrBb..'], 12,
    'The small echo pocket is off to the left. Work around the red shelf, then open the green bud into yellow.',
    { specials: [bud(0, 3, 'Y'), ...echoes(2, 1, 2), ...echoes(3, 1, 2)] }),
  level(53, 'Ribbon on the River', 'The ribbon willow',
    ['OOoYYBBbB', 'OOYYPpBB', '.OO.PPBB.', '..GGPP..', '..Gg.YY..', '...GGY..'], 12,
    'The purple echo ribbon runs down the right branch. The two ceiling buds open into different colors, so keep track of their little rims.',
    { specials: [bud(0, 2, 'P'), bud(0, 7, 'G'), ...echoes(1, 4, 5), ...echoes(2, 4, 5), ...echoes(3, 4, 5), dew(2, 1)] }),
  level(54, 'Mabel’s Braided Bend', 'The stepping-stone flight',
    ['..rRRGG..', '..RRGG..', '..PPYY...', '..PPYY..', '...BBB...', '..BB....', '.........'], 13,
    'The dotted route turns left through an echo patch and ends at a red bud. Open each gate from below, saving room to match the bud’s yellow layer.',
    { specials: [bud(0, 2, 'Y'), ...echoes(2, 2, 3), ...echoes(3, 2, 3)], flightPath: path([6, 3], [5, 3], [4, 3], [3, 2], [2, 2], [1, 2], [0, 2]) }),
  level(55, 'Petals on the Footbridge', 'The little brook bridge',
    ['RRr...GgG', 'RR.YY.GG', '.RRYYYGG.', '.PPPBBB.', '..Pp.Bb..', '...YYY..', '....yY...'], 13,
    'The yellow bridge holds two colored baskets. An echo pop opens the purple basket; both ceiling buds still need their second match.',
    { specials: [bud(0, 2, 'Y'), bud(0, 7, 'B'), ...echoes(3, 1, 2, 3), ...echoes(4, 2, 3), pollen(6, 4)] }),
  level(56, 'The Forked Reed', 'The fork in the stream',
    ['..YyYPP..', '..YYPP..', '..GgBB...', '..GGBb..', '.RR..YY..', '.rR..yY.', '..R...Y..'], 13,
    'Two thin stems carry the lower reeds. The yellow bud opens into green, while a blue pop can reach the purple echo crown.',
    { specials: [bud(0, 3, 'G'), ...echoes(0, 5, 6), ...echoes(1, 4, 5)] }),
  level(57, 'A Raft of Replies', 'The reed raft',
    ['RrRYYYBbB', 'RRYYYYBB', '.RRGGGBB.', '..GGPP..', '..PpG....', '..PPG...', '...gG....'], 14,
    'The marked raft carries a purple echo pair beside green cargo. Its move can change the contact you are planning; the top red bud opens into green too.',
    { specials: [bud(0, 1, 'G'), ...echoes(4, 2, 3), ...echoes(5, 2, 3), dew(0, 7)], wind: { row: 4, start: 2, length: 3 } }),
  level(58, 'The Dewleaf Tunnel', 'The brook’s shaded tunnel',
    ['OOoPpPGGG', 'OOPPPPGG', '.OO...GG.', '.YY..BB.', '.YYY.BBB.', '..yY.bb.', '...YYB...'], 14,
    'The echo roof can borrow a color through a touching pop. Crack the two dew leaves, then use the middle window to return to the orange bud.',
    { specials: [bud(0, 2, 'P'), ...echoes(0, 3, 4, 5), ...echoes(1, 2, 3, 4, 5), dew(2, 1), dew(2, 7), hc(3, 3), hc(3, 4)] }),
  level(59, 'A Bow Above the Brook', 'The willow-ribbon bend',
    ['RrR...BbB', 'RR.GG.BB', '.RRGGGBB.', '..PpPP..', '..YY.YY..', '.yy...yy'], 14,
    'The broad echo bow sits between two yellow skirts. Try a touching pop before spending shots on its visible color; the ceiling buds need purple and green next.',
    { specials: [bud(0, 1, 'P'), bud(0, 7, 'G'), ...echoes(3, 2, 3, 4, 5), pollen(4, 5)] }),
  level(60, 'Brookside Lanterns', 'The bridge into Lantern Wood',
    ['OOoYYYgGG', 'OOPpPPGG', '.OO..GG..', '.BB..BB.', '.BBB.BBB.', '..Bb.Pp.', '...PPP...', '...pP...'], 15,
    'The upper echo braid can open a bank-shot window. Watch the little purple raft below while you rescue both bud bees at the ceiling.',
    { specials: [bud(0, 2, 'P'), bud(0, 6, 'B'), ...echoes(1, 2, 3, 4, 5), dew(0, 4), pollen(7, 3)], wind: { row: 6, start: 3, length: 3 } }),

  level(61, 'The First Warm Lantern', 'The lantern-wood welcome',
    ['...YyY...', '...YY...', '..GGGGG..', '..GgGGG.', '.RR..BB..', '.rR..Bb.'], 11,
    'Take a breath under the first lantern. The ceiling bud becomes green, and the green echo collar can answer either lower branch.',
    { specials: [bud(0, 4, 'G'), ...echoes(3, 2, 3, 4, 5)] }),
  level(62, 'Shelves of Fireflies', 'The lantern shelves',
    ['RRr...PPP', 'RR...PPp', '.RR.GGPP.', '.YY.GgG.', '..YYBB...', '..yYBb..'], 13,
    'The tall echo shelf has a bee near its outer edge. A touching green pop can light the shelf; keep a bank open to the red bud on the other side.',
    { specials: [bud(0, 2, 'Y'), ...echoes(0, 6, 7, 8), ...echoes(1, 5, 6, 7), ...echoes(2, 6, 7), pollen(5, 2)] }),
  level(63, 'A String of Small Lights', 'The lantern string',
    ['..GgG.BBB', '..GG..BB', '..YY.PPBB', '..Yy.Pp.', '.RR..PP..', '.rR..YY.', '..R..yY..'], 13,
    'The lantern string bends down the right side. A yellow pop beside its lowest loop can carry color upward through the echo cluster.',
    { specials: [bud(0, 3, 'Y'), ...echoes(2, 5, 6), ...echoes(3, 5, 6), ...echoes(4, 5, 6)] }),
  level(64, 'Mabel’s Firefly Walk', 'The lantern flight lane',
    ['...PpP...', '..RRPP..', '.RRYYGG..', '.RRYYGG.', '..BBGG...', '..BB....', '.........'], 14,
    'Mabel follows a gentle zigzag. Open the blue step, then choose the yellow route or the green echo side before returning to the bud.',
    { specials: [bud(0, 4, 'Y'), ...echoes(3, 5, 6), ...echoes(4, 4, 5)], flightPath: path([6, 3], [5, 3], [4, 3], [3, 3], [2, 4], [1, 4], [0, 4]) }),
  level(65, 'Windows for the Lanterns', 'The old lantern keeper’s gate',
    ['RRrYYYBbB', 'RR....BB', '.PP...GG.', '.Pp...gG', '..YY.YGG.', '..yY.Yy.', '...Y.Y...'], 14,
    'The empty middle makes room for banks. The left echo pocket can open from yellow, while the right bud opens into green.',
    { specials: [bud(0, 2, 'P'), bud(0, 7, 'G'), ...echoes(2, 1, 2), ...echoes(3, 1, 2), hc(1, 3), hc(1, 4)] }),
  level(66, 'A Lantern on the Water', 'The lantern bowl',
    ['OOo...GgG', 'OO.YY.GG', '.OOYYYGG.', '.PPPBBB.', '..PPBB...', '..pPB...', '...BB....'], 14,
    'The blue echo lantern reaches down to the water. Watch the small mixed raft move, then choose whether to open a bud or cut the bowl’s support.',
    { specials: [bud(0, 2, 'P'), bud(0, 7, 'B'), ...echoes(3, 4, 5, 6), ...echoes(4, 4, 5), echo(5, 4), ...echoes(6, 3, 4), pollen(4, 2)], wind: { row: 5, start: 2, length: 3 } }),
  level(67, 'The Circle of Fireflies', 'The firefly ring',
    ['...RrR...', '..RRRR..', '.YYPPYY..', '.YyPPYy.', '.GG..BB..', '.gG..Bb.', '..G...B..'], 15,
    'The two dew bees sit beside one echo centre. A touching pop can open the centre and crack a shell, but each bee still needs its color cleared.',
    { specials: [bud(0, 4, 'P'), ...echoes(2, 3, 4), ...echoes(3, 3, 4), dew(3, 2), dew(3, 6)] }),
  level(68, 'The Lantern Trapdoor', 'The keeper’s hollow',
    ['RrRPpPGGG', 'RRPPPPGG', '.RR..GG..', '.BB..YY.', '..BBYY...', '..bByY..', '...PP....'], 15,
    'The echo roof holds a little bee, and the comb makes a trapdoor below. Leave an open middle for a return shot to the red bud.',
    { specials: [bud(0, 1, 'P'), ...echoes(0, 3, 4, 5), ...echoes(1, 2, 3, 4, 5), hc(2, 3), hc(2, 4)] }),
  level(69, 'Lights High and Low', 'The lantern hillside',
    ['RRrYYYbBB', 'RR....BB', '.RR.PPBB.', '..GGPp..', '..GGYY...', '.RR..YY.', '.Rr...Yy.', '..R...Y.'], 15,
    'The hillside has small rescue pockets at different heights. Open the echo turn in the middle, then bank toward whichever ceiling bud fits your next color.',
    { specials: [bud(0, 2, 'G'), bud(0, 6, 'P'), ...echoes(2, 4, 5), ...echoes(3, 4, 5), dew(6, 2)] }),
  level(70, 'Lanterns in the Leaves', 'The path to the canopy',
    ['GGgrRRPpP', 'GGYyYYPP', '.GG..PP..', '.BB..BB.', '.BBY.BBB.', '..bBYYb.', '..YYYY...', '...yY...'], 16,
    'The yellow echo bridge opens the upper branches. There are three ceiling bees to bring along: two buds and a dew bee between them.',
    { specials: [bud(0, 2, 'Y'), bud(0, 7, 'B'), dew(0, 3), ...echoes(1, 2, 3, 4, 5), pollen(7, 3)] }),

  level(71, 'A View Between the Branches', 'The canopy welcome',
    ['RRr...GgG', 'RR....GG', '.RR...GG.', '..PP.PP.', '..Pp.Pp..', '...BBB..', '....bB...'], 12,
    'Two echo pockets hang above one blue nest. Open either side, then return to the ceiling buds through the window you made.',
    { specials: [bud(0, 2, 'P'), bud(0, 7, 'B'), ...echoes(3, 2, 3, 5, 6), ...echoes(4, 2, 3, 5, 6)] }),
  level(72, 'The Robin’s Staircase', 'The robin’s nesting steps',
    ['..YyY....', '..YYYY..', '...RRPP..', '...RrPp.', '....GGP..', '....GG..', '...BBB...', '...bB...'], 14,
    'The staircase leans to the right. Its echo rail can open from green or red, while the top bud needs a red second match.',
    { specials: [bud(0, 3, 'R'), ...echoes(2, 5, 6), ...echoes(3, 5, 6), echo(4, 6)] }),
  level(73, 'Wind Above the Glen', 'The swaying treetop bridge',
    ['GGgPpPBBB', 'GGPPPPBB', '.GG...BB.', '.YY..YY.', '..YYRR...', '..yYRR..', '...rR....'], 14,
    'The lower yellow-and-red strip can sway into a new support. Open the echo crown, then leave a bank to the green bud’s red layer.',
    { specials: [bud(0, 2, 'R'), ...echoes(0, 3, 4, 5), ...echoes(1, 2, 3, 4, 5), hc(2, 3), hc(2, 4), hc(2, 5)], wind: { row: 4, start: 2, length: 4 } }),
  level(74, 'Mabel Among the Branches', 'The robin’s flight lane',
    ['..RrRGG..', '..RRPP..', '.YYPPBB..', '.YYPPBB.', '..GGBB...', '..GG....', '.........'], 15,
    'Mabel climbs through the middle echo braid. Her last stop is a red bud that becomes yellow; open it before clearing the final route space.',
    { specials: [bud(0, 3, 'Y'), ...echoes(1, 4, 5), ...echoes(2, 3, 4), ...echoes(3, 3, 4)], flightPath: path([6, 3], [5, 3], [4, 3], [3, 3], [2, 3], [1, 3], [0, 3]) }),
  level(75, 'The Honeycomb Hammock', 'The canopy hammock',
    ['OoO...PpP', 'OO....PP', '.OOYYYPP.', '..YYGG..', '.BB..GG..', '.Bb..Gg.', '..B...G..'], 15,
    'The hammock has two honeycomb edges and a yellow echo sling. A touching green pop may open the sling before you tackle the two bud bees.',
    { specials: [bud(0, 1, 'Y'), bud(0, 7, 'G'), ...echoes(2, 3, 4, 5), ...echoes(3, 2, 3), hc(3, 0), hc(3, 7)] }),
  level(76, 'The Robin’s Rafters', 'The little treetop house',
    ['RrR...BbB', 'RR.GG.BB', '.RRgGGBB.', '.PPPYYY.', '..PpYy...', '...PPY..', '....YY...'], 15,
    'The echo rafter bends into the yellow nest. Crack the green dew bee on the beam, then return to the red and blue buds above.',
    { specials: [bud(0, 1, 'G'), bud(0, 7, 'Y'), ...echoes(3, 1, 2, 3), ...echoes(4, 2, 3), ...echoes(5, 3, 4), dew(2, 3)] }),
  level(77, 'A Cradle in the Canopy', 'The tall willow cradle',
    ['...GGgGG.', '...GGGG.', '..RR..PP.', '..Rr..Pp', '.BB....P.', '.Bb...PP', '..BB.PP..', '...YYY..', '....yY...'], 16,
    'The cradle has a long echo handle and two low pockets. Open a side rather than filling the bottom, and keep room for the top bud’s yellow layer.',
    { specials: [bud(0, 5, 'Y'), ...echoes(2, 6, 7), ...echoes(3, 6, 7), echo(4, 7), ...echoes(5, 6, 7), ...echoes(6, 5, 6), pollen(8, 4)] }),
  level(78, 'Dewleaf Lookout', 'The treetop lookout',
    ['OOoYyYgGG', 'OOYYYYGG', '.OO...GG.', '.PP..BB.', '..PPPBB..', '..pPBB..', '...BBB...', '....bB..'], 16,
    'The left echo leaf can borrow blue or orange through a touching pop. The top yellow dew bee and both buds reward leaving a clear bank-shot lane.',
    { specials: [bud(0, 2, 'P'), bud(0, 6, 'B'), dew(0, 4), ...echoes(3, 1, 2), ...echoes(4, 2, 3, 4), ...echoes(5, 2, 3)] }),
  level(79, 'A Knot in the Treetops', 'The canopy ribbon knot',
    ['RRrPPPBBb', 'RRPpPPBB', '.RR..BB..', '.GG..YY.', '.GGG.YYY.', '..gG.yY.', '...GGY...', '...gGy..'], 16,
    'The echo ribbon opens the comb window. The mixed lower raft can loosen a hanging pocket; both ceiling buds still need their own next colors.',
    { specials: [bud(0, 2, 'G'), bud(0, 8, 'Y'), ...echoes(0, 3, 4, 5), ...echoes(1, 2, 3, 4, 5), hc(2, 3), hc(2, 4)], wind: { row: 6, start: 3, length: 3 } }),
  level(80, 'Above All the Leaves', 'The highest little clearing',
    ['rRRYPYBBb', 'RRYPYPBB', '.RRPPBB..', '.GG..GG.', '..GGYGG..', '..gGyg..', '..YYYYY..', '...yY...'], 17,
    'The small echo centre and the chameleon offer two ways through the crown. Watch the chameleon’s next color while opening the outer buds.',
    { specials: [bud(0, 0, 'G'), bud(0, 8, 'Y'), echo(0, 4), echo(1, 3), ...echoes(2, 3, 4), chameleon(1, 5, 'Y'), pollen(6, 4)] }),

  level(81, 'The First Orchard Star', 'The starlit-orchard welcome',
    ['...PpP...', '...PP...', '.YYYYY...', '.YyYYY..', '..GG.RR..', '..gG.Rr.', '...G.R...'], 12,
    'Start gently under the first star. A lower pop can wake the yellow echo collar, and the purple bud becomes yellow too.',
    { specials: [bud(0, 4, 'Y'), ...echoes(3, 1, 2, 3, 4, 5)] }),
  level(82, 'A Crescent of Apples', 'The crescent apple tree',
    ['RRrYYYGGG', 'RR...YGG', '.RR.PPYY.', '..GGPpY.', '..GG.PP..', '..gG.RR.', '...G.Rr..'], 14,
    'The echo branch curves around a window. A yellow pop can reach its upper end, while green can reach below; the red bud opens into green.',
    { specials: [bud(0, 2, 'G'), ...echoes(2, 4, 5), ...echoes(3, 4, 5), ...echoes(4, 5, 6), dew(6, 6)] }),
  level(83, 'Two Baskets of Stars', 'The orchard basket bridge',
    ['BBb...PpP', 'BB.RR.PP', '.BBRrRPP.', '.YY..YY.', '..YYGYY..', '..yYGy..', '...GGG...', '...gG...'], 15,
    'The red echo bridge holds two yellow baskets. Open the bridge from a touching pop, then choose the ceiling bud that fits your next bubble.',
    { specials: [bud(0, 2, 'G'), bud(0, 7, 'Y'), ...echoes(1, 3, 4), ...echoes(2, 3, 4, 5), pollen(7, 3)] }),
  level(84, 'Mabel’s Twilight Turn', 'The twilight flight lane',
    ['..GGpPP..', '..GGPP..', '.RRYYBB..', '.RRYYBB.', '..PPPBB..', '..PP....', '.........'], 15,
    'Mabel turns through the yellow middle before reaching a purple bud. The red echo pocket can open an outside approach to the upper gate.',
    { specials: [bud(0, 4, 'Y'), ...echoes(2, 1, 2), ...echoes(3, 1, 2)], flightPath: path([6, 4], [5, 3], [4, 3], [3, 3], [2, 4], [1, 4], [0, 4]) }),
  level(85, 'A Few Shooting Stars', 'The wishing-tree branches',
    ['rRR...BbB', 'RR.PP.BB', '.RRPpPBB.', '.GG..YY.', '..GGGYY..', '..gG.yY.', '...PPP...', '...pP...'], 15,
    'A pop beside the central echo cluster can open a high window. The left bud opens into yellow; the right ceiling bee has a dew shell.',
    { specials: [bud(0, 0, 'Y'), dew(0, 7), ...echoes(1, 3, 4), ...echoes(2, 3, 4, 5)] }),
  level(86, 'The Moonlit Rocker', 'The orchard rocking branch',
    ['OOoYYYpPP', 'OOYYYYPP', '.OO..PP..', '.GG..BB.', '.GGG.BBB.', '..gGYb..', '...YYY...', '...yY...'], 16,
    'The yellow rocker sways every two shots. A green or yellow pop can answer the blue echo branch; the two buds open into green and blue.',
    { specials: [bud(0, 2, 'G'), bud(0, 6, 'B'), ...echoes(3, 5, 6), ...echoes(4, 5, 6, 7), echo(5, 5), pollen(5, 4)], wind: { row: 6, start: 3, length: 3 } }),
  level(87, 'Stars Caught in the Canopy', 'The apple-tree crown',
    ['GGgRrRBBb', 'GGPPPPBB', '.GGPpBB..', '.YY..YY.', '..YYGYY..', '..yYGGy.', '...GGG...', '...gG...'], 16,
    'The echo crown gives a route toward three ceiling bees. The red one has dew, while the outer buds open into purple and yellow.',
    { specials: [bud(0, 2, 'P'), bud(0, 8, 'Y'), dew(0, 4), ...echoes(1, 2, 3, 4, 5), ...echoes(2, 3, 4)] }),
  level(88, 'A Loop of Orchard Wishes', 'The wishing-tree loop',
    ['RrR...PpP', 'RR....PP', '.RRYYYPP.', '..YyYY..', '.GG..BB..', '.gG..Bb.', '..GG.BB..', '...YYY..', '....yY...'], 16,
    'The yellow echo loop holds a long hanging picnic. Open the loop or work around either side, leaving a return lane for the two buds.',
    { specials: [bud(0, 1, 'G'), bud(0, 7, 'B'), ...echoes(2, 3, 4, 5), ...echoes(3, 2, 3, 4, 5), hc(4, 3), hc(4, 4), pollen(8, 4)] }),
  level(89, 'A Wish in the Wind', 'The orchard’s breezy rise',
    ['...YYyYY.', '..PPYYYY', '..Pp.RR..', '..GG.Rr.', '..GG.BB..', '..gG.Bb.', '...G.B...', '...PPP..'], 17,
    'The little purple raft can slide under the two thin stems. Open the left echo pocket, then climb toward the yellow bud and its purple second layer.',
    { specials: [bud(0, 5, 'P'), ...echoes(1, 2, 3), ...echoes(2, 2, 3), pollen(7, 4)], wind: { row: 7, start: 3, length: 3 } }),
  level(90, 'The Orchard’s Goodnight', 'The last apple-tree arch',
    ['rRRYyYbBB', 'RRYYYYBB', '.RRPpBB..', '.GGPPGG.', '.GG..GG..', '..gG.Gg.', '...RRR...', '...rR...'], 17,
    'The middle echo arch opens a route around the comb. Watch the red raft while preparing a green match for the left bud and purple for the right.',
    { specials: [bud(0, 0, 'G'), bud(0, 6, 'P'), dew(0, 4), ...echoes(2, 3, 4), ...echoes(3, 3, 4), hc(4, 3), hc(4, 4)], wind: { row: 6, start: 3, length: 3 } }),

  level(91, 'The Cottage Comes into View', 'The homeward welcome',
    ['GGg...PpP', 'GG....PP', '.GGYYYPP.', '..YYBB..', '..yYBb...'], 12,
    'A small rescue to start the walk home. The green bud opens into yellow, while the purple echo branch can answer the yellow bridge.',
    { specials: [bud(0, 2, 'Y'), ...echoes(0, 6, 7, 8), ...echoes(1, 6, 7), ...echoes(2, 6, 7)] }),
  level(92, 'Curtains for the Porch', 'Bramble’s porch window',
    ['RRrPPPBBb', 'RRPpPPBB', '.RRYYBB..', '.GGYYGG.', '..GgYgG..', '...YY...', '....yY...'], 15,
    'The echo curtain opens from a touching yellow or red pop. Both ceiling buds remain after their first match, so keep an approach to each corner.',
    { specials: [bud(0, 2, 'G'), bud(0, 8, 'Y'), ...echoes(0, 3, 4, 5), ...echoes(1, 2, 3, 4, 5)] }),
  level(93, 'Postcards for the Picnic', 'The cottage letter tree',
    ['RRr...YyY', 'RR.PP.YY', '.RRPpPYY.', '..GGBB..', '.GG..BBB.', '.Gg...bB', '..G..BB..', '...RRR..', '....rR...'], 16,
    'The postcard tree has pockets at three heights. Open the echo bridge first or trim a lower support, then return to the green and blue bud layers.',
    { specials: [bud(0, 2, 'G'), bud(0, 7, 'B'), ...echoes(1, 3, 4), ...echoes(2, 3, 4, 5), pollen(8, 4)] }),
  level(94, 'Mabel’s Last Little Bend', 'The cottage flight path',
    ['..rRRGG..', '..RRPP..', '.YYPPBBB.', '.YYGGBBB', '.GGGYY...', '..GGY...', '.........'], 16,
    'Follow the bend up the left side of the middle. The echo pocket opens an extra approach, and the last red bud becomes yellow.',
    { specials: [bud(0, 2, 'Y'), ...echoes(1, 4, 5), ...echoes(2, 3, 4)], flightPath: path([6, 3], [5, 3], [4, 3], [3, 2], [2, 2], [1, 2], [0, 2]) }),
  level(95, 'The Front-Door Knot', 'The cottage garden gate',
    ['RrRYyYBbB', 'RRYYYYBB', '.RR..BB..', '.PP..GG.', '..PPGGGG.', '..pPGgg.', '...YYY...', '...yY...'], 16,
    'The purple echo ribbon can open the left side of the comb window. Crack the yellow ceiling bee while making paths back to both bud layers.',
    { specials: [bud(0, 1, 'P'), bud(0, 7, 'G'), dew(0, 4), ...echoes(3, 1, 2), ...echoes(4, 2, 3), ...echoes(5, 2, 3), hc(2, 3), hc(2, 4)] }),
  level(96, 'Wind on the Welcome Mat', 'The cottage stepping stones',
    ['RRrPPPYYy', 'RRPpPPYY', '.RR..YY..', '.GG..BBB', '.GGGG.BB.', '..gGRb..', '...RRR...', '...rR...'], 17,
    'The mixed welcome-mat strip shifts every two shots. Open the purple echo curtain, then match green and blue to finish the outer buds.',
    { specials: [bud(0, 2, 'G'), bud(0, 8, 'B'), ...echoes(0, 3, 4, 5), ...echoes(1, 2, 3, 4, 5)], wind: { row: 5, start: 2, length: 4 } }),
  level(97, 'Teacups for Everyone', 'The cottage tea table',
    ['..GGgGG..', '..GGGG..', '.RRPPBB..', '.RrPpBb.', '.YY..YY..', '.yY..Yy.', '..YY.YY..', '...RRR..', '....rR...'], 17,
    'Two dew bees sit beside the echo teacup. Open the middle or drop the lower saucers, then match the purple layer of the top bud.',
    { specials: [bud(0, 4, 'P'), ...echoes(2, 3, 4), ...echoes(3, 3, 4), dew(3, 2), dew(3, 6), pollen(8, 4)] }),
  level(98, 'Bramble’s Welcome Garland', 'The cottage garland',
    ['rRRPpPgGG', 'RRPPPPGG', '.RRYYGG..', '..YYBB..', '.RR..BBB.', '.Rr...bB', '..RR.BB..', '...YYY..', '....yY...'], 17,
    'The echo garland stretches across the roof. The small red raft can loosen a low branch; the ceiling buds open into yellow and blue.',
    { specials: [bud(0, 0, 'Y'), bud(0, 6, 'B'), ...echoes(0, 3, 4, 5), ...echoes(1, 2, 3, 4, 5), pollen(8, 4)], wind: { row: 6, start: 2, length: 2 } }),
  level(99, 'One More Little Rescue', 'The cottage reunion path',
    ['RRrYyYbBB', 'RRPPPPBB', '.RRPpBB..', '.GG..YY.', '.GGG.YYY.', '..gG.yY.', '...PPY...', '...pPy..'], 18,
    'There is time for every friend. Open the echo braid and the comb window, crack the yellow ceiling bee, then return to the buds’ green and yellow layers.',
    { specials: [bud(0, 2, 'G'), bud(0, 6, 'Y'), dew(0, 4), ...echoes(1, 2, 3, 4, 5), ...echoes(2, 3, 4), hc(3, 3), hc(3, 4)], wind: { row: 6, start: 3, length: 3 } }),
  level(100, 'Every Friend Comes Home', 'Home with Bramble',
    ['rRRgYYBBb', 'RRPPPPBB', '.RRPpBB..', '.GGYYGG.', '.GG..GG..', '.gG..Gg.', '..BB.RR..', '..bBYRr.', '...YYY...'], 18,
    'Bring the picnic home one step at a time. The echo braid opens the centre; drop the comb supports, watch the little blue raft, and give both ceiling buds their second match.',
    { specials: [bud(0, 0, 'P'), bud(0, 8, 'Y'), dew(0, 3), ...echoes(1, 2, 3, 4, 5), ...echoes(2, 3, 4), hc(4, 3), hc(4, 4), pollen(8, 4)],
      wind: { row: 6, start: 2, length: 2 }, flightPath: path([8, 4], [7, 4], [6, 4], [5, 3], [4, 3], [3, 3], [2, 4], [1, 4], [0, 4]),
      tutorial: 'One last lovely rescue. Use the paths you have learned: ordinary matches, falling supports, two-layer buds and echo ripples. There is plenty of room to take it one friend at a time.' })
];
